# Generated by Django 5.0 on 2024-01-03 07:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 시간")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 시간")),
                ("deleted_at", models.DateTimeField(null=True, verbose_name="삭제 시간")),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "아티클",
                "verbose_name_plural": "아티클",
            },
        ),
    ]
